# Generated by Django 2.2.28 on 2025-03-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('points', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('quizzes_created', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_ID', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Movies And TV', 'Movies And TV'), ('Animals', 'Animals'), ('General Knowledge', 'General Knowledge'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiztopia.User')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiztopia.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiztopia.Question')),
            ],
        ),
    ]
